### ISSUE TITLE
Removed option causing errors when deploying

### ISSUE THREAD

**Issue by vdombrovski** [open-io/ansible-role-openio-sds#53]
The following option has been removed on kernels 4.12 upward:

https://github.com/open-io/ansible-role-openio-sds/blob/4fbda068a4682e1277257b4adcf911e0609f0171/defaults/main.yml#L92

We need to either: ignore errors when setting sysctl parameters, or set it conditionally

**Comment by racciari** [comment]
Done in PR #67 
Thanks.
